[versions]
lsp4j = "0.24.0"
coroutines = "1.10.2"
ktor = "3.2.3"

[libraries]
org-eclipse-lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines"}
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor"}
